// Assembly WQFree.Cache, Version 1.0.0.0

[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Reflection.AssemblyTitle("WQFree.IPCCache")]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("上海易迅电子商务发展有限公司")]
[assembly: System.Reflection.AssemblyProduct("WQFree.IPCCache")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 上海易迅电子商务发展有限公司 2010")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("689df432-1bed-4b9c-891c-13b7a2d63d1a")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")] 
